APP_NAME = 'Image Library'
VERSION = '4.0'
DB_SETUP_FILE = 'app/data_access/setup.sql'
CONFIG_FILE = 'config.ini'
ERROR_LOG_FILE = 'logs/errors.log'
ICONS_DIR = 'app/assets/icons/'
LANG_DIR = 'app/assets/lang/'
IMAGE_FILE_EXTENSIONS = ['png', 'jpg', 'jpeg', 'bmp', 'gif']
MIN_THUMB_SIZE = 50
MAX_THUMB_SIZE = 2000
MIN_THUMB_LOAD_THRESHOLD = 0
MAX_THUMB_LOAD_THRESHOLD = 1000
