%import common.WS_INLINE

%ignore WS_INLINE

NAME: /\w+/
REGEX: /([\w.*-]|\\ )+/

?query: tag | metatag | or | and | p_query

p_query: "(" query ")" -> group
       | "-" p_query   -> negation

or: (tag | metatag | and | p_query) ("+" (tag | metatag | and | p_query))+ -> disjunction

and: (tag | metatag | p_query) (tag | metatag | p_query)+ -> conjunction

tag: NAME    -> tag
   | "-" tag -> negation

metatag: NAME ":" REGEX -> metatag
        | "-" metatag   -> negation
